image: gitpod/workspace-full

ports:
  - port: 8080
    onOpen: open-preview

tasks:
  - init: 
      pip install -r requirements.txt &&
      cp contrib/env_sample .env &&
      python /workspace/ca/manage.py migrate &&
      python /workspace/ca/manage.py createsuperuser --username admin --email a@a.com --no-input
    command: 
      python /workspace/ca/manage.py runserver 0.0.0.0:8080

github:
  prebuilds:
    # enable for the master/default branch (defaults to true)
    master: true